using System.Collections.Generic;
using Helpers.UIGrid;
namespace BLL.Query.Reports.ReportColumns
{
    public class vwStudyGSKKPIV2_Columns : IReportColumns
    {
        public UIGridProperties GetReportColumns()
        {
            return 
            new UIGridProperties{
                //CodeBlockStart

Title = "Study GSK KPI",
FilterGroup = 1,
Columns = new List<UIGridColumn>{new UIGridColumn{field="studyIconNumber",  header ="ICON Number" }, 
new UIGridColumn{field="studyName",  header ="Study Name" }, 
new UIGridColumn{field="region",  header ="Region" }, 
new UIGridColumn{field="portfolio",  header ="Portfolio" }, 
new UIGridColumn{field="specialProject",  header ="Special Project", align="center" }, 
new UIGridColumn{field="sponsor",  header ="Sponsor" }, 
new UIGridColumn{field="studyStatusText",  header ="Study Status" }, 
new UIGridColumn{field="currentDmpmManager",  header ="DIR" }, 
new UIGridColumn{field="currentDmpm",  header ="DMPM" }, 
new UIGridColumn{field="cdms",  header ="CDMS" }, 
new UIGridColumn{field="odmName",  header ="ODM Name" }, 
new UIGridColumn{field="odmNameComment",  header ="ODM Name Comment" }, 
new UIGridColumn{field="rcdLocationValue",  header ="RDC Location" }, 
new UIGridColumn{field="rcdLocationComment",  header ="RDC Location Comment" }, 
new UIGridColumn{field="compoundName",  header ="Compound Name" }, 
new UIGridColumn{field="compoundNameComment",  header ="Compound Name Comment" }, 
new UIGridColumn{field="activeStatus",  header ="Active Study" }, 
new UIGridColumn{field="activeStatusComment",  header ="Active Study Comment" }, 
new UIGridColumn{field="firstCentreInitation",  header ="First Centre Initation Date", type="date", format="dd-MMM-yyyy", align="Center" }, 
new UIGridColumn{field="firstCentreInitationComment",  header ="First Centre Initation Date Comment" }, 

new UIGridColumn{field="gskPriorityCategory",  header ="GSK Priority Category" }, 
new UIGridColumn{field="gskPriorityCategoryComment",  header ="GSK Priority Category Comment" }, 

new UIGridColumn{field="eCrfSpecification",  header ="eCRF specifications before final sign off during database set-up" }, 
new UIGridColumn{field="eCrfSpecificationComment",  header ="eCRF specifications before final sign off during database set-up Comment" }, 
new UIGridColumn{field="eCrf",  header ="eCRF before final sign off during database set-up" }, 
new UIGridColumn{field="eCrfComment",  header ="eCRF before final sign off during database set-up Comment" }, 
new UIGridColumn{field="iDrf",  header ="iDRP before final sign off during database set-up" }, 
new UIGridColumn{field="iDrfComment",  header ="iDRP before final sign off during database set-up Comment" }, 
new UIGridColumn{field="plannedClinicalDatabaseSetupDate",  header ="Planned Clinical Database Setup Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="plannedClinicalDatabaseSetupDateComment",  header ="Planned Clinical Database Setup Date Comment" }, 
new UIGridColumn{field="actualClinicalDatabaseSetupDate",  header ="Actual Clinical Database Setup Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="actualClinicalDatabaseSetupDateComment",  header ="Actual Clinical Database Setup Date Comment" }, 

new UIGridColumn{field="plannedDataCollectionToolsGoliveDate",  header ="Planned Data Collection tools go-live Date" }, 
new UIGridColumn{field="plannedDataCollectionToolsGoliveDateComment",  header ="Planned Data Collection tools go-live Date Comment" }, 
new UIGridColumn{field="actualDataCollectionToolsGoliveDate",  header ="Actual Data Collection tools go-live Date" }, 
new UIGridColumn{field="actualDataCollectionToolsGoliveDateComment",  header ="Actual Data Collection tools go-live Date Comment" }, 


new UIGridColumn{field="edcPgl",  header ="EDC PGL" }, 
new UIGridColumn{field="edcPglComment",  header ="EDC PGL Comment" }, 
new UIGridColumn{field="dmIssues",  header ="EDC PGL due to DM issues caused by CRO" }, 
new UIGridColumn{field="dmIssuesComment",  header ="EDC PGL due to DM issues caused by CRO Comment" }, 
new UIGridColumn{field="dmRequeries",  header ="Total DM re-queries" }, 
new UIGridColumn{field="dmRequeriesComment",  header ="Total DM re-queries Comment" }, 
new UIGridColumn{field="dmQueries",  header ="Total DM queries" }, 
new UIGridColumn{field="dmQueriesComment",  header ="Total DM queries Comment" }, 
new UIGridColumn{field="reprogrammingDueToDmIssue1",  header ="Reprogramming due to DM issue 1" }, 
new UIGridColumn{field="reprogrammingDueToDmIssue1Comment",  header ="Reprogramming due to DM issue 1 Comment" }, 
new UIGridColumn{field="activeMacros1",  header ="Total active macros across study 1" }, 
new UIGridColumn{field="activeMacros1Comment",  header ="Total active macros across study 1 Comment" }, 

new UIGridColumn{field="noProgramModsNonsdtmDueToIconError",  header ="# Program MODS Non-SDTM due to ICON error" }, 
new UIGridColumn{field="noProgramModsNonsdtmDueToIconErrorComment",  header ="# Program MODS Non-SDTM due to ICON error Comment" }, 
new UIGridColumn{field="noOfDataReviewMeetingPerYear",  header ="# of Data Review meeting per year" }, 
new UIGridColumn{field="noOfDataReviewMeetingPerYearComment",  header ="# of Data Review meeting per year Comment" }, 

new UIGridColumn{field="averageNoDays",  header ="Average no. of days from query response to closure" }, 
new UIGridColumn{field="averageNoDaysComment",  header ="Average no. of days from query response to closure Comment" }, 
new UIGridColumn{field="noOfDaysTaken",  header ="No. of days it has taken from query response to closure" }, 
new UIGridColumn{field="noOfDaysTakenComment",  header ="No. of days it has taken from query response to closure Comment" }, 
new UIGridColumn{field="dataPoint",  header ="No. of days it has taken for the first DM query for the data point" }, 
new UIGridColumn{field="dataPointComment",  header ="No. of days it has taken for the first DM query for the data point Comment" }, 
new UIGridColumn{field="protocolAmendmentSignoff",  header ="Protocol Amendment signoff Date", type="date", format="dd-MMM-yyyy" }, 
new UIGridColumn{field="protocolAmendmentSignoffComment",  header ="Protocol Amendment signoff Date Comment", align="center" }, 
new UIGridColumn{field="protocolAmendmentNumber",  header ="Protocol Amendment Number" }, 
new UIGridColumn{field="protocolAmendmentNumberComment",  header ="Protocol Amendment Number Comment" }, 
new UIGridColumn{field="lastSubjectLastVisit",  header ="Last Subject Last Visit", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="lastSubjectLastVisitComment",  header ="Last Subject Last Visit Comment" }, 
new UIGridColumn{field="plannedECrfLockDate",  header ="Planned eCRF Lock Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="plannedECrfLockDateComment",  header ="Planned eCRF Lock Date Comment" }, 
new UIGridColumn{field="actualECrfLockDate",  header ="Actual eCRF Lock Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="actualECrfLockDateComment",  header ="Actual eCRF Lock Date Comment" }, 
new UIGridColumn{field="plannedSoftLockDate",  header ="Planned Soft Lock Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="plannedSoftLockDateComment",  header ="Planned Soft Lock Date Comment" }, 
new UIGridColumn{field="actualSoftLockDate",  header ="Actual Soft Lock Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="actualSoftLockDateComment",  header ="Actual Soft Lock Date Comment" }, 
new UIGridColumn{field="finalLabDate",  header ="Final Lab Data", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="finalLabDateComment",  header ="Final Lab Data Comment" }, 
new UIGridColumn{field="plannedDbFreezeDate",  header ="Planned Database Freeze Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="plannedDbFreezeDateComment",  header ="Planned Database Freeze Date Comment" }, 
new UIGridColumn{field="actualDbFreezeDate",  header ="Actual Database Freeze Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="actualDbFreezeDateComment",  header ="Actual Database Freeze Date Comment" }, 

new UIGridColumn{field="dbfLessthenPlanedNoWeeksNoLabData",  header ="DBF <= Planned # weeks (no lab data)" }, 
new UIGridColumn{field="dbfLessthenPlanedNoWeeksNoLabDataComment",  header ="DBF <= Planned # weeks (no lab data) Comment" }, 
new UIGridColumn{field="dbfLessthenPlannedNoWeeksWithLabData",  header ="DBF <= Planned # weeks (with lab data)" }, 
new UIGridColumn{field="dbfLessthenPlannedNoWeeksWithLabDataComment",  header ="DBF <= Planned # weeks (with lab data) Comment" }, 

new UIGridColumn{field="noOfDmUnlocks",  header ="No. of DM unlocks" }, 
new UIGridColumn{field="noOfDmUnlocksComment",  header ="No. of DM unlocks Comment" }, 
new UIGridColumn{field="noOfNonDmUnlocks",  header ="No. of nonDM unlocks" }, 
new UIGridColumn{field="noOfNonDmUnlocksComment",  header ="No. of nonDM unlocks Comment" }, 
new UIGridColumn{field="reasonForUnlock",  header ="Reason for Unlock" }, 
new UIGridColumn{field="reasonForUnlockComment",  header ="Reason for Unlock Comment" }, 
new UIGridColumn{field="totalNoOfDbUnfreeze",  header ="Total Database Unfreeze" }, 
new UIGridColumn{field="totalNoOfDbUnfreezeComment",  header ="Total Database Unfreeze Comment" }, 
new UIGridColumn{field="dateOfApprovedCsr",  header ="Date of approved CSR", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="dateOfApprovedCsrComment",  header ="Date of approved CSR Comment" }, 
new UIGridColumn{field="archivalStatus",  header ="Archival status completed date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="archivalStatusComment",  header ="Archival status completed date Comment" }, 
new UIGridColumn{field="csrSignoff",  header ="Date of CSR Sign-off", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="csrSignoffComment",  header ="Date of CSR Sign-off Comment" }, 
new UIGridColumn{field="informDecommissioning",  header ="InForm Decommissioning Completed Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="informDecommissioningComment",  header ="InForm Decommissioning Completed Date Comment" }, 
new UIGridColumn{field="timeProtocolApprovalPlanned",  header ="Planned Protocol Approval", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeProtocolApprovalActual",  header ="Actual Protocol Approval", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeCrfapprovalPlanned",  header ="Planned CRF Approval", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeCrfapprovalActual",  header ="Actual CRF Approval", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeEdcscreensGoLivePlanned",  header ="Planned EDC Screens Golive", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeEdcscreensGoLiveActual",  header ="Actual EDC Screens Golive", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeDmpsignedOffPlanned",  header ="Planned DMPM Signed Off", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeDmpsignedOffActual",  header ="Actual DMP Signed Off", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeCdmsgolivePlanned",  header ="Planned CDMS Golive", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeCdmsgoLiveActual",  header ="Actual CDMS Golive", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFpiPlanned",  header ="Planned FPI", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFpiActual",  header ="Actual FPI", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeSdtmgoLivePlanned",  header ="Planned SDTM Golive Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeSdtmgoLiveActual",  header ="Actual SDTM Golive Date", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeLpiPlanned",  header ="Planned LPI", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeLpiActual",  header ="Actual LPI", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeLpoPlanned",  header ="Planned LPO", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeLpoActual",  header ="Actual LPO", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="time25percentPtcleanPlanned",  header ="Planned 25% PT Clean", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="time25percentPtcleanActual",  header ="Actual 25% PT Clean", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeMainSoftLockPlanned",  header ="Planned Main Soft Lock Type", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeMainSoftLockActual",  header ="Actual Main Soft Lock", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeMainDblPlanned",  header ="Planned Main DBL", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeMainDblActual",  header ="Actual Main DBL", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpLpoPlanned",  header ="Planned FollowUp LPO", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpLpoActual",  header ="Actual FollowUp LPO", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpSoftLockPlanned",  header ="Planned FollowUp SoftLock", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpSoftLockActual",  header ="Actual FollowUp SoftLock", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpDblPlanned",  header ="Planned FollowUp DBL", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFollowUpDblActual",  header ="Actual FollowUp DBL", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFinalTmfarchivedPlanned",  header ="Planned Final TMF Archived", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="timeFinalTmfarchivedActual",  header ="Actual Final TMF Archived", type="date", format="dd-MMM-yyyy", align="center" }, 
new UIGridColumn{field="builddonebyIconPid",  header ="Database Build by ICON", align="center" }}
//CodeBlockEnd
            };
        }
    }
}
